### ISSUE TITLE
MKTABLES.C and DEBUGTBL.INC are out of sync with each other.

### ISSUE THREAD

**Issue by RockBrentwood** [Baron-von-Riedesel/DOS-debug#10]
MKTABLES.C doesn't produce DEBUGTBL.INC. One or both of the versions of these files distributed with the software is not correct.

Lines 1119 and 1121 generate lines in DEBUGTBL.INC starting in "---", instead of in ";---" - you're missing a semi-colon in the strings in the print statements. Line 1032 generates "SPARSE_BASE\tequ ..." at the end of the previously-generated line, because it's missing a newline. The string should be "\nSPARSE_BASE\tequ".

There are other discrepancies, but these prevent the program (MKTABLES.C) from even compiling or the generated program file (DEBUGTBL.INC) from compiling.

**Comment by Baron-von-Riedesel** [comment]
Indeed. It's been a long time that I run mktables.exe - I guess I regarded is as already obsolete, since it was planned to be removed.

Also, as I had to realize, using MS VC does create an executable that's not working as expected.
