### ISSUE TITLE
Typo in new R86M interrupt 0Ch handler

### ISSUE THREAD

**Issue by ecm-pushbx** [Baron-von-Riedesel/DOS-debug#12]
https://github.com/Baron-von-Riedesel/DOS-debug/blob/9d1f4449b8d427f7a08720c0bce89681903cc44e/src/TRAPR.INC#L69

This reads `in al, 10h` but should be `in al, 20h` I believe.

**Comment by Baron-von-Riedesel** [comment]
Yes - I discovered that in the meantime. Thanks for reporting!

**Comment by ecm-pushbx** [comment]
Fixed in https://github.com/Baron-von-Riedesel/DOS-debug/commit/9c4f6ef91c406d0f8c6dcaf225e51c09d1c0cc78#diff-3f24c5a513b2e33db66bab0f38c1feb4b8d210d1fc127c7759e491b56bef6feaL70
