### ISSUE TITLE
Scratch selector bugs fixed in lDebugX today

### ISSUE THREAD

**Issue by ecm-pushbx** [Baron-von-Riedesel/DOS-debug#13]
I think the following bugs are applicable to the current Debug/X as well:

* C command should display original selector, and needn't use scratchsel (IsWriteableBX) at all: https://hg.pushbx.org/ecm/ldebug/rev/73b70e98afea
* E command needs scratchsel (like used by getaddrW and IsWriteableBX) but should still display original selector (using getaddrR): https://hg.pushbx.org/ecm/ldebug/rev/3e355d997d75
* Use case can corrupt scratchsel limit which then causes eg DM command to segfault: https://hg.pushbx.org/ecm/ldebug/rev/0ee74639badc (I tested this in your latest DebugX release from the github releases, and can cause a GPF.)
* A command, like E command, should display original selector but use IsWriteableBX to actually write the assembled machine code

Honourable mention to the bug in parsecm that you figured out in your latest revision, I picked that up for https://hg.pushbx.org/ecm/ldebug/rev/c9dd1b27f2a2

**Comment by ecm-pushbx** [comment]
That was missing the link to the aa fix: https://hg.pushbx.org/ecm/ldebug/rev/5f3e9ce65c55

**Comment by ecm-pushbx** [comment]
Another bug: If the addition in https://hg.pushbx.org/ecm/fddebug/file/30d695b48654/DEBUG.ASM#l6988 carries then iswriteablecseip will detect a failure to write. Fixed in https://hg.pushbx.org/ecm/ldebug/rev/60357e2ef014

And for another, IsWriteableBX returns a status in CF but all callers of getaddrW (including getrangeW) ignore it. Fixed in https://hg.pushbx.org/ecm/ldebug/rev/96fa72814b0a Though you do comment in https://hg.pushbx.org/ecm/fddebug/file/30d695b48654/DEBUG.ASM#l7006 that you intentionally omitted the dispatching on the error status. But if the 31.000C call in IsWriteableBX fails (is that possible?) then you will have bx == scratchsel upon the CY return, which is probably not what you want.

**Comment by Baron-von-Riedesel** [comment]
In the last commit that getaddrW/R and getrangeW/R distinction has been removed ( call IsWriteableBX isn't done at that "low-level" anymore ). Will have to check that "DM bug" yet.

**Comment by Baron-von-Riedesel** [comment]
e cmd no longer shows scratch sel.
