### ISSUE TITLE
Two remaining enter mode bugs

### ISSUE THREAD

**Issue by ecm-pushbx** [Baron-von-Riedesel/DOS-debug#5]
[As I commented](https://github.com/Baron-von-Riedesel/DOS-debug/pull/4#issuecomment-1061871826) there are two more bugs in the current ([1.28 release](https://github.com/Baron-von-Riedesel/DOS-debug/releases/tag/v1.28)) build of Debug/X.

The first bug listed there is fixed by [your commit](https://github.com/Baron-von-Riedesel/DOS-debug/commit/a4439a1fa44f1549865df77a2e38c8d76b057fdc).

The second bug and the third bug still exist. The second one is that after entering a new value then minus, the new value is ignored instead of writing it to memory. The third one is that in a 32-bit segment, only the lower 16 bits of the offset are incremented or decremented, causing a wrap-around instead of stepping into another 64 KiB block.

**Comment by Baron-von-Riedesel** [comment]
the inc/dec bug has been fixed. Actually, I changed the handling on a basic level, since the "default" flag of the descriptor attributes has no meaning for the size of a segment. Whenever a segment's limit exceeds 64 kB ( in protected-mode ), there will/should be no wrap-around.

**Comment by Baron-von-Riedesel** [comment]
byte value before '-' no longer skipped now.
