### ISSUE TITLE
Discrepancy between original DEBUG and DOS-debug

### ISSUE THREAD

**Issue by ijean** [Baron-von-Riedesel/DOS-debug#9]
Hi,

I found a discrepancy (possible bug) between original debug from MS-DOS 6.22 and the DOS-debug 1.29.
Steps to reproduce it:

* original DEBUG
```
> debug
-h 8 FFF8
0000  0010
```

* DOS-debug
```
> debug
-h 8 FFF8
0010000  0010
```

It looks to me that the operations are not done on 16 bits integers like on the original DEBUG program.

Regards,
Jean

**Comment by ecm-pushbx** [comment]
[My fork lDebug](https://pushbx.org/ecm/web/#projects-ldebug) has introduced an option to make the H command output compatible to MS-DOS Debug (for valid values). This must be enabled specifically however:

```
-r dco2 or= 1000
-h 1 2
0003  FFFF
-
```

**Comment by Baron-von-Riedesel** [comment]
Yes, Debug/X, as it is described in readme, has additional features, so it cannot be 100% compatible.
